// commands/verite.js
// Commande Slash /vérité qui affiche une question aléatoire dans un salon spécifique
const { SlashCommandBuilder } = require('discord.js');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('vérité')
        .setDescription('Pose une question aléatoire à répondre sincèrement (uniquement dans le salon autorisé)'),
    async execute(interaction) {
        // Vérifier si la commande est utilisée dans le salon autorisé
        const veriteChannelId = process.env.VERITE_CHANNEL_ID;
        if (!veriteChannelId) {
            console.error('[Vérité] Erreur : VERITE_CHANNEL_ID non défini dans .env');
            return interaction.reply({
                content: 'Erreur : Salon non configuré. Contactez un administrateur.',
                ephemeral: true
            });
        }

        if (interaction.channelId !== veriteChannelId) {
            return interaction.reply({
                content: `Cette commande ne peut être utilisée que dans le salon <#${veriteChannelId}>.`,
                ephemeral: true
            });
        }

        // Liste des questions
        const questions = [
            'Est-ce que tu portes des sous-vêtements si vieux qu’ils ont des trous dedans ?',
            'Quelle est ta chanson inavouable ?',
            'Est-ce que tu as déjà été jaloux ou jalouse d’un ami ?',
            'Pour quelle raison as-tu pleuré la dernière fois ?',
            'Quelle est la chose la plus ridicule que tu aies jamais faite ?',
            'Comment te vengerais-tu d’une personne qui t’a blessé(e) ?',
            'Est-ce que tu as déjà fait semblant d’être malade pour ne pas sortir avec tes amis ?',
            'Est-ce que tu as déjà eu un béguin pour la petite amie ou pour le copain d’un ou d’une ami(e) ?',
            'Si quelqu’un t’offrait 100 000 €, que ferais-tu avec ?',
            'Si tu avais une urgence, quelle est la première personne que tu appellerais ?',
            'Est-ce que tu as déjà révélé le secret de l’un de tes amis à quelqu’un d’autre ?',
            'Quel est le pire mensonge que tu aies dit à ton ou ta meilleur(e) ami(e) ?',
            'As-tu déjà fait quelque chose susceptible de décevoir tes parents ?',
            'Est-ce que tu as déjà essayé de ruiner la relation amoureuse de l’un ou l’une de tes ami(e)s ?',
            'Est-ce que tu as déjà fait quelque chose de bizarre seulement pour te faire remarquer de quelqu’un ?',
            'Est-ce que tu as peur du noir ?',
            'Est-ce que tu t’es déjà moqué de ton frère ou de ta sœur derrière leur dos ?',
            'Quel est ton pire défaut ?',
            'Si tu étais invisible pendant une journée, qui espionnerais-tu ?',
            'Quelle ton habitude la plus dégoûtante ?',
            'Quelle est la chose la plus embarrassante vécue pendant un rendez-vous romantique ?',
            'Est-ce que tu as déjà été infidèle ?',
            'Quelle est la pire chose que tu aies faite en rompant avec quelqu’un ?',
            'Est-ce que quelqu’un t’a déjà posé un lapin ?',
            'Est-ce que tu aimes envoyer des photos coquines ?',
            'Combien de fois as-tu été amoureux(se) ?',
            'Est-ce que tu sortirais avec une personne qui a plus de 20 ans que toi ?',
            'Est-ce que tu as déjà regardé des films coquins ?',
            'Peux-tu entretenir une relation amoureuse si vous ne faites pas l’amour ?',
            'Est-ce que tu es déjà sorti(e) avec quelqu’un par pitié ?',
            'Combien de partenaires intimes as-tu eu ?',
            'Est-ce que tu rêves de trouver le grand amour ?',
            'Fais-tu confiance à ta ou ton copine ou copain actuel(le) ?',
            'Quelle est la pire vengeance que tu aies prise après une rupture ?',
            'Où est-ce que tu préfères être embrassé(e) ?',
            'As-tu déjà fait pleurer quelqu’un ? Si oui pourquoi ?',
            'As-tu des phobies ?',
            'Quelle est la chose que personne ne connaît à propos de toi ?',
            'Avec qui aimerais-tu renouer le contact ?',
            'Qui regrettes-tu d’avoir laissé partir ?',
            'Quelle relation t’a le plus changé ?',
            'Où espères-tu être dans ta vie dans 5 ou 10 ans ?',
            'Où voudrais-tu voyager ?',
            'Veux-tu avoir des enfants ? Combien ?',
            'Est-ce que tu as envie de te marier ?',
            'Quel est le plus grand rêve que tu as mais que tu as honte d’avouer ?',
            'As-tu peur de vieillir ?',
            'Quel aliment ne mangerais-tu pas, quelques soient les circonstances ?',
            'As-tu menti ce soir ?',
            'Est-ce que tu risquerais ta vie pour quelqu’un ?',
            'Est-ce que tu as déjà été attiré(e) par quelqu’un d’autre que ton ou ta partenaire actuel(le) ?',
            'Est-ce que tu ressens encore quelque chose pour l’un ou l’une de tes partenaires ?',
            'Quelle est la chose la plus stupide que tu aies faite par amour ?',
            'Est-ce que tu préfères dormir nu(e) ou en pyjamas ?',
            'Est-ce que tu as déjà fait semblant d’être amoureux(se) ?',
            'Qu’est-ce qui est le plus important pour toi : ta famille, tes amis ou ta moitié ?',
            'Qui a le plus d’influence sur toi ?',
            'Quelle est ta pire bêtise étant enfant ?',
            'Il te reste 24h à vivre, qu’est-ce que tu fais ?',
            'Qu’est-ce que tu détestes chez toi ?',
            'Si c’était la fin du monde et que tu ne pouvais sauver qu’une seule personne, qui ce serait ?',
            'Qu’est-ce qui ne manquera jamais dans ton frigo ?',
            'Si tu pouvais ramener une personne décédée à la vie, qui ce serait ?',
            'Raconte-nous un secret de ton enfance',
            'Quelle est la célébrité que tu trouves le plus beau ?',
            'Crois-tu au destin ?',
            'Crois-tu au coup de foudre ?',
            'Quelle est la pire chose qui puisse t’arriver ?',
            'Que penses-tu d’Emmanuel Macron ?',
            'As-tu un tatouage ? Si oui où et sinon aimerais-tu en avoir un ?',
            'Lequel des 7 péchés capitaux dirige ta vie ?',
            'Quel est ton film préféré ?',
            'Tu préfèrerais ne plus boire ou ne plus manger ?',
            'Quel prénom aurais-tu aimé avoir ?',
            'As-tu déjà menti à tes parents ?',
            'Quel est ton surnom ?',
            'Quel a été ton cauchemar le plus effrayant ?',
            'As-tu déjà triché à l’école ?',
            'As-tu déjà menti sur ton âge ?',
            'Quelle est ta musique préférée ?',
            'Quelle est ta citation préférée ?',
            'Quelle est la chose la plus drôle qui te soit arrivée ?',
            'Quel est le pire message que tu aies reçu ?',
            'Si tu pouvais être quelqu’un d’autre pour une journée, qui aimerais-tu être ?',
            'Si tu pouvais créer une loi que tout le monde devrait appliquer, quelle serait-elle ?',
            'Quelle est ta pire mauvaise habitude ?',
            'As-tu déjà menti sur ton CV pour trouver un emploi ?',
            'Quelle était ton émission de télévision préférée quand tu étais enfant ?',
            'Quelles ont été les pires vacances de ta vie ?',
            'As-tu déjà oublié l’anniversaire d’une personne spéciale ?',
            'Quelle était ta matière préférée à l’école ?',
            'Quel est le travail que tu ne voudrais jamais faire ?',
            'Quel est ton sport préféré ?',
            'Qu’est-ce qui te rend furieux ?',
            'Quel était le nom de ton premier amour ?',
            'Quel âge avais-tu pour ta première histoire ?',
            'Quel est le meilleur moment de la journée pour toi ?',
            'As-tu déjà volé quelque chose ?',
            'Quel est le pire cadeau que tu aies jamais reçu ?',
            'Quelle est la chose la plus folle que tu ferais par amour ?',
            'Combien de fois as-tu fugué de la maison ?',
            'Qui était ton premier amour de célébrité ?',
            'Si tu pouvais vivre n’importe où dans le monde, où vivrais-tu ?',
            'Quel a été le meilleur jour de ta vie et pourquoi ?',
            'Quelle est la chose la plus embarrassante que tes parents t’ont surprise en train de faire ?',
            'Si tu pouvais échanger ta vie avec quelqu’un pour un jour, qui serait-ce et pourquoi ?',
            'Quelle est la rumeur la plus ridicule que tu aies entendue à propos de toi ?',
            'Si tu pouvais magiquement parler couramment une langue, laquelle choisirais-tu et pourquoi ?',
            'Quelle est la décision la plus impulsive que tu aies jamais prise, et cela a-t-il été un bon ou un mauvais choix ?',
            'As-tu des talents cachés ? Lesquels ?',
            'Si tu pouvais être un athlète professionnel, quel sport pratiquerais-tu et pourquoi ?',
            'Quelle est la chose la plus aventureuse que tu aies jamais faite ?',
            'Si tu ne pouvais manger qu’un seul aliment pour le reste de ta vie, quel serait-il ?',
            'Que aimes-tu faire quand tu es seul ?',
            'Quel est le pire aliment que tu aies jamais mangé ?',
            'Quel personnage de fiction aimerais-tu être et pourquoi ?',
            'Quand as-tu présenté des excuses sincères pour la dernière fois, et pourquoi ?',
            'Quelle a été ton expérience la plus douloureuse ?',
            'As-tu déjà été impliqué dans une bagarre physique avec quelqu’un ? Si oui, raconte toute l’histoire !',
            'Envisagerais-tu d’utiliser une fausse carte d’identité ?',
            'Quelle est la chose la plus folle que tu ferais pour un million de dollars ?',
            'Préférerais-tu pouvoir voler ou avoir une vision à rayons X ?',
            'Si tu étais bloqué sur une île déserte et ne pouvais emmener qu’une seule personne, qui serait-ce ?',
            'Si tu pouvais retourner dans le passé, quel conseil donnerais-tu à ton jeune toi ?',
            'As-tu déjà été tellement embarrassé que tu voulais disparaître ?',
            'Quelle est la chose la plus folle que tu as faite pour essayer d’impressionner quelqu’un ?',
            'As-tu déjà publié quelque chose sur les réseaux sociaux que tu regrettes ? C’était quoi ?',
            'Si ta vie avait une chanson thème, quelle serait-elle ?',
            'Évalue-toi de 1 à 10 sur combien tu te trouves attirant.',
            'Quel est ton béguin de célébrité le plus embarrassant ?',
            'As-tu déjà dû faire caca dans des toilettes publiques sans papier ? Qu’as-tu fait ?',
            'Quelle phrase d’accroche utiliserais-tu si tu rencontrais ton béguin de célébrité ?',
            'Quelle est la chose la plus chère que tu aies jamais achetée, et le regrettes-tu ?',
            'Quel est le moment le plus inapproprié où tu as éclaté de rire ?',
            'Combien de temps as-tu déjà passé sans prendre de douche ?',
            'Quelle est la blague la plus drôle que tu aies jamais faite à quelqu’un ?',
            'As-tu déjà eu un béguin pour un de tes professeurs ? Si oui, qui était-ce ?',
            'Quel personnage fictif aimerais-tu épouser ?',
            'Quelle est la chose la plus étrange à laquelle tu es émotionnellement attaché ?',
            'Que penses-tu être la chose la plus étrange à propos de ta famille ?',
            'As-tu menti pendant ce jeu aujourd’hui, et nous l’avons manqué ?',
            'Quel est le cadeau le moins cher que tu aies jamais offert à quelqu’un ?',
            'Combien de temps as-tu été puni le plus longtemps, et pourquoi ?',
            'As-tu déjà été impliqué dans des bagarres à l’école ?',
            'Quelle est la pire chose que tu aies jamais faite à quelqu’un ?',
            'Quel est ton souvenir d’enfance le plus embarrassant ?',
            'Quelle est la pire rumeur que tu as crue sans savoir qu’elle n’était pas vraie ?',
            'Quelle est la blague la plus dégoûtante que tu aies jamais entendue ?',
            'Préférerais-tu ne jamais manger de chocolat ou ne jamais refaire l’amour ?',
            'Quel est le plat le plus bizarre que tu aies secrètement aimé manger ?',
            'Quel est le nom d’utilisateur le plus gênant que tu aies jamais utilisé pour un compte en ligne ?',
            'Quel est un mot ou une expression que tu as complètement mal compris pendant trop longtemps ?',
            'Quelle est une chanson que tu adores chanter à tue-tête quand tu es sûr que personne d’autre n’écoute ?',
            'Qu’est-ce qui n’est pas du tout effrayant mais qui te fait quand même flipper ?',
            'Quelle est la chose la plus embarrassante que tu aies jamais recherchée sur Google ?',
            'Si tu pouvais être n’importe quel dinosaure, lequel serais-tu et pourquoi ?',
            'Aimerais-tu te blottir contre la personne à ta gauche ?',
            'Quelle est la pire histoire de tricherie que tu aies jamais entendue ?',
            'As-tu déjà eu un ami imaginaire ?',
            'Quelle est la question que tu crains le plus de répondre honnêtement ?',
            'Quelle chanson as-tu honte d’admettre que tu aimes ?',
            'Raconte-nous ta pire histoire de beuverie !',
            'Qu’est-ce que tu aimes et que la plupart des gens n’aiment pas ?',
            'Qui choisirais-tu si tu devais assassiner trois personnes dans le monde ?',
            'As-tu déjà envoyé un texto à la mauvaise personne, et c’était quoi ?',
            'Quelle est la situation la plus embarrassante dans laquelle tu as pété ?',
            'Quelle est la chose la plus ridicule sur laquelle tu as menti ?',
            'Si tu devais participer à une émission de télé-réalité, ce serait laquelle ?',
            'Quelle est la chose la plus illégale que tu aies jamais faite ?',
            'Si tu pouvais commettre un crime sans être pris, ce serait quoi ?',
            'Quelle est la drogue la plus dure que tu ferais jamais ?',
            'Quel est le nom de ton premier béguin ?',
            'Qui est la personne la plus surprenante à t’avoir écrit en privé ?',
            'Comment survivrais-tu à une apocalypse zombie ?',
            'Si tu devais abandonner un de tes sens, lequel ce serait ?',
            'Quelle est la chose que tu ne ferais pas même si quelqu’un t’offrait plus d’argent que tu ne pourrais jamais dépenser ?',
            'Qu’as-tu fait que tu espères que tes parents ne découvrent jamais ?',
            'Que veux-tu faire quand tu seras grand ?',
            'Quelle est ta matière préférée et pourquoi ?',
            'Qui est ton personnage de dessin animé préféré, et pourquoi ?',
            'Où aimerais-tu passer tes vacances d’été ?',
            'Qui est ton professeur préféré ?',
            'Quelle est ta couleur préférée ?',
            'Si tu étais un super-héros, qui serais-tu ?',
            'Qui est ton personnage Disney préféré ?',
            'Quelle a été ton expérience la plus embarrassante jusqu’à présent ?',
            'Que ferais-tu avec 1 000 $ ?',
            'Si tu pouvais rencontrer une célébrité, qui choisirais-tu et pourquoi ?',
            'As-tu déjà triché lors d’un examen ?',
            'Quand as-tu nettoyé ta chambre pour la dernière fois ?',
            'As-tu déjà pleuré pendant un film ? Si oui, lequel ?',
            'Que fais-tu quand tu es triste ?',
            'Veux-tu être célèbre quand tu seras grand ? Pourquoi ou pourquoi pas ?',
            'Que aimes-tu faire quand tu t’ennuies à la maison ?',
            'Qu’est-ce qui te fait le plus rire ?',
            'Avec qui passes-tu le plus de temps ?',
            'Quelle a été la meilleure fête d’anniversaire que tu aies jamais eue ? Pourquoi était-elle si géniale ?',
            'As-tu déjà refusé un biscuit, et pourquoi ?',
            'Qui est ton meilleur ami ?',
            'As-tu déjà regardé un film ou une émission de télévision que tu sais que tu n’es pas autorisé à regarder ?',
            'Quels sont les mots les plus drôles que tu connais ?',
            'Quel est ton talent secret ?',
            'Crois-tu ou as-tu déjà cru aux fées des dents ?',
            'Qui choisirais-tu si tu devais épouser un personnage Disney ?',
            'Si tu pouvais avoir n’importe quel animal comme animal de compagnie, lequel serait-ce et pourquoi ?',
            'Quelle est la chose la plus ridicule que tu aies faite devant ta famille ?',
            'Si tu pouvais échanger ta vie avec celle d’un de tes amis pour une journée, qui serait-ce et pourquoi ?',
            'As-tu déjà essayé de prendre un dessert supplémentaire quand tes parents ne regardaient pas ?',
            'Quelle est la chose la plus aventureuse que tu aies faite sur un terrain de jeu ?',
            'Si tu pouvais avoir un pouvoir magique pour une journée, lequel serait-ce et comment l’utiliserais-tu ?',
            'As-tu déjà cassé quelque chose et accusé quelqu’un d’autre ?',
            'Préférerais-tu vivre dans un monde de magie ou de super-héros ?',
            'Que choisirais-tu si tu devais choisir un nouveau nom pour toi-même ?',
            'Si tu pouvais être n’importe quel animal, lequel serais-tu ?',
            'Quel aliment mangerais-tu tous les jours si tu le pouvais ?',
            'As-tu essayé de contrefaire la signature de tes parents ?',
            'Prends-tu des en-cas en cachette quand tes parents ne regardent pas ?',
            'Quelles sont les dates d’anniversaire des membres de ta famille ?',
            'Si tu pouvais partir en vacances avec ta famille n’importe où dans le monde, où choisirais-tu et pourquoi ?',
            'Quel était ton surnom d’enfance ?',
            'À quoi ressemblent tes pyjamas préférés ?',
            'Quelle est la première lettre du nom de ton béguin ?',
            'Comment était ton premier baiser ?',
            'Que ferais-tu si tu savais qu’il n’y aurait aucune conséquence ?',
            'Quelle est la chose la plus enfantine que tu fais encore ?',
            'Quelle est ta chanson préférée d’un boys band ?',
            'Quel est ton bien le plus précieux ?',
            'Selon toi, quel est le plus grand défi auquel les adolescents sont confrontés aujourd’hui ?',
            'Si tu pouvais revivre un jour de ta vie, quel jour ce serait ?',
            'Quelle pense-tu sera ta plus grande réussite dans la vie ?',
            'Qu’as-tu récemment appris sur toi-même qui t’a surpris ?',
            'Si tu pouvais avoir un âge pour toujours, quel âge choisirais-tu ? Pourquoi ?',
            'Quelle est la plus grosse erreur que tu aies jamais faite ?',
            'Quel est l’événement le plus embarrassant qui t’est arrivé à l’école ?',
            'Quelle est la tenue la plus embarrassante que tu aies portée à l’école ?',
            'Si tu pouvais posséder ton propre commerce un jour, quel serait-il ?',
            'Quel considères-tu être ton plus grand défaut ?',
            'As-tu déjà utilisé ton argent de poche pour autre chose que le déjeuner ?',
            'As-tu déjà menti à ton meilleur ami ? Si oui, quand ?',
            'Envisagerais-tu de faire de la chirurgie plastique ? Si oui, que ferais-tu ?',
            'Qu’est-ce que ton partenaire fait qui te fait toujours rire ?',
            'À quel animal comparerais-tu ton partenaire au lit ?',
            'Quand as-tu regardé du porno pour la dernière fois ?',
            'Si tu ne pouvais faire l’amour que dans une seule position pendant un mois, quelle position choisirais-tu ?',
            'Comment sais-tu que ton partenaire passe une mauvaise journée ?',
            'Qu’aimes-tu le plus dans le corps de ton partenaire ?',
            'Quelle a été ta première impression de ton partenaire ?',
            'Quel est ton endroit préféré pour être avec ton partenaire ?',
            'De quelles manières être en relation avec ton partenaire t’a-t-il changé en tant que personne ?',
            'À quelle fréquence te masturbes-tu ?',
            'Comment quelqu’un peut-il obtenir ton pardon s’il t’a fait du tort par le passé ?',
            'Quel est le secret d’un partenariat réussi ?',
            'Que admires-tu chez ton partenaire ?',
            'Quelles sont tes plus grandes peurs concernant les relations ?',
            'As-tu déjà simulé un orgasme ?',
            'Quelle est la chose la plus immature que tu fais ?',
            'Quelle est ta position sexuelle préférée ?',
            'À quel âge as-tu perdu ta virginité ?',
            'Préférerais-tu être la grande cuillère ou la petite cuillère ?',
            'Qu’est-ce qui te rend jaloux ?',
            'Qu’est-ce qui t’ennuie chez ton partenaire ?',
            'Si tu devais changer une chose physique chez toi, quelle serait-elle ?',
            'Quelle est la chose que tu ne renoncerais jamais, quoi qu’il arrive ?',
            'Quels sont tes plus grands excitants et tes plus grands tue-l’amour ?',
            'Quel est l’endroit le plus fou où tu as fait l’amour ?',
            'Quand et comment as-tu fait l’amour pour la première fois ?',
            'Qu’aimes-tu le plus chez ton partenaire ?',
            'Quelle est ta façon préférée de recevoir de l’amour de la part de ton partenaire ?',
            'Quelle est ton idée d’un rendez-vous parfait ?',
            'Préférerais-tu sortir avec quelqu’un de plus jeune ou de plus âgé que toi ?',
            'Quand as-tu pensé à moi pour la dernière fois ?',
            'Si tu pouvais aller n’importe où en vacances, où choisirais-tu et pourquoi ?',
            'Envisagerais-tu d’avoir une relation ouverte ?',
            'Que penses-tu des démonstrations publiques d’affection ?',
            'Quel vêtement penses-tu que je porte le mieux ?',
            'Que penses-tu du sexting et de l’envoi de photos coquines ?',
            'Quel est l’endroit le plus risqué où tu as fait l’amour ?',
            'Qu’est-ce qui te excite le plus au lit ?',
            'Quelle est ta meilleure qualité en tant que partenaire ?',
            'Qu’aimes-tu le plus chez moi ?',
            'Quel est pour toi un critère rédhibitoire instantané ?',
            'Quelle est ta préférence, câliner ou embrasser ?',
            'Quelle est la chose que tu ne ferais jamais au lit ?',
            'Qu’est-ce que tu trouves romantique que d’autres peuvent ne pas trouver ?',
            'Aimes-tu être l’initiateur ou celui qui est poursuivi ?',
            'As-tu déjà été amoureux de plusieurs personnes à la fois ?',
            'Quelles qualités trouves-tu les plus attirantes chez un partenaire potentiel ?',
            'Comment tes meilleurs amis te décriraient-ils ?',
            'Quelle est la compétence la plus inutile que tu trouves attirante ?',
            'As-tu déjà fait du nudisme ?',
            'Quels sont les trois traits de caractère que ton partenaire idéal devrait avoir ?',
            'Qu’est-ce qui te fait toujours rire ?',
            'Quelles sont les trois choses sans lesquelles tu ne pourrais pas vivre ?',
            'Quelle est une idée fausse courante à propos de toi ?',
            'Qu’est-ce qui te rend vraiment heureux ?',
            'Qu’est-ce que tu trouves attirant que d’autres peuvent ne pas trouver ?',
            'Quel est l’âge le plus vieux avec lequel tu sortirais ?',
            'T’es-tu déjà fait surprendre en flagrant délit ? Par qui ?',
            'Qu’est-ce que tu préfères chez ton/ta partenaire ?',
            'Es-tu déjà sortie avec plusieurs personnes en même temps ?',
            'As-tu déjà pris un râteau ?',
            'As-tu déjà appelé un(e) ex lorsque tu étais saoul ?',
            'As-tu déjà envoyé des photos de toi nu(e) ?',
            'Qu’est-ce qui t’excite le plus ?',
            'Quelle est cette chose que tu ne fais que lorsque personne ne te voit ?',
            'Quel est ton petit plaisir inavouable ?',
            'Quelle est la chose la plus bizarre que tu aies mangée ?',
            'Quelle est la situation la plus gênante dans laquelle tu t’es retrouvé ?',
            'T’es-tu déjà fait pipi dessus ?',
            'Quelle est ton histoire de fête la plus folle ?',
            'Où est-ce que tu préfères péter en public ?',
            'As-tu déjà surpris tes parents en train de faire l’amour ?',
            'Que ferais-tu si tu restais enfermé(e) dans un magasin toute la nuit ?',
            'Quelle est la chose la plus étrange que tu fais quand tu es ivre ?',
            'Quelle est la chose la plus dégoutante que tu aies jamais faite ?',
            'Crois-tu aux extraterrestres ?',
            'Qu’est-ce qui te fait perdre tout intérêt pour quelqu’un instantanément ?',
            'Quelle a été la plus grande différence d’âge dans tes relations amoureuses ?',
            'Quel acte sexuel maitrises-tu le mieux ?',
            'As-tu déjà eu des relations sexuelles en avion ?',
            'As-tu déjà nagé nu ?',
            'Quel est l’endroit le plus insolite où tu as eu des relations sexuelles ?',
            'As-tu déjà fait semblant d’atteindre l’orgasme ?',
            'Quelle est la chose la plus gênante qui t’est arrivée pendant un rapport sexuel ?',
            'As-tu des fantasmes particuliers ?',
            'Préfères-tu faire l’amour avec les lumières allumées ou éteintes ?',
            'Quelle est ton histoire de coup d’un soir la plus folle ?',
            'Quel est ton plaisir coupable au lit ?',
            'Quel est ton plus gros secret ?',
            'As-tu déjà ghosté quelqu’un ?',
            'Quelle est la technique de drague la plus audacieuse que tu aies tentée ?',
            'Comment évalues-tu ton apparence sur une échelle de 1 à 10 ?',
            'As-tu un secret que tu n’as jamais révélé à quelqu\'un ? Lequel ?',
            'As-tu un frère ou une sœur que tu préfères ?',
            'Y a-t-il un(e) ami que tu considères comme ton préféré ?',
            'Quelle est la pire chose que tu aies faite dans ta vie ?',
            'Si tu devais enterrer un corps, qui appellerais-tu à l’aide ?',
            'Quelle est la chose que tu ne ferais jamais, même pour 1 million d’euros ?',
            'Quelle est la pire chose que tu aies jamais dite à quelqu’un ?',
            'Quelle est ta plus grande insécurité ?',
            'Quel est l’endroit le plus insolite où tu t’es soulagé ?',
            'As-tu déjà uriné sous la douche ?',
            'Quel est le plat le plus étrange que tu aies jamais concocté ?',
            'Quelle est ta combinaison de nourriture la plus bizarre (et un peu dégoutante) ?',
            'Quelle est la rumeur la plus farfelue que tu aies entendue à ton sujet ?',
            'Quelle habitude n’as-tu que lorsque tu es seul(e) ?',
            'Combien de selfies est-ce que tu prends en moyenne chaque jour ?',
            'Qu’est-ce qui te dégoute le plus chez les autres ?',
            'Quel est ton record de jours sans passer sous la douche ?',
            'As-tu un crush sur une célébrité improbable ?',
            'Quelle est la chose la plus surprenante que tu as dans ton sac ?',
            'Quelle partie de mon corps te plait le plus ?',
            'Quelle est ta plus grande crainte à propos de nous ?',
            'Quelle était ta première impression quand on s’est rencontrés ?',
            'Quel fantasme aimerais-tu que l’on explore ensemble ?',
            'Comment voyais-tu ton partenaire idéal quand tu étais plus jeune ?',
            'Où te vois-tu avec moi dans 10 ans ?',
            'Décris-moi ta soirée romantique parfaite.',
            'Quelle activité que l’on fait ensemble te plait le plus ?',
            'Si on s’était connus plus tôt, crois-tu que l’on aurait été ensemble ?',
            'Qu’est-ce que tu apprécies le plus chez moi ?',
            'Quelles sont les 3 positions que tu préfères ?',
            'Pour toi, c’est quoi tromper quelqu’un ?',
            'Quel est, selon toi, le secret d’une relation épanouie ?',
            'Est-ce que je t’ai déjà fait verser des larmes ?',
            'Que penses-tu sincèrement de mes amis ?',
            'Quelle est la dernière chose que vous avez cherchée sur votre téléphone ?',
            'Quelle est la première chose que vous feriez si vous vous réveilliez un jour avec le sexe opposé ?',
            'Vrai ou faux ? Vous avez le coup de foudre pour [remplir le blanc].',
            'À quoi pensez-vous lorsque vous êtes assis sur les toilettes ?',
            'Quel est votre plaisir coupable ?',
            'Quelle est votre pire habitude ?',
            'As-tu déjà essayé de prendre une photo sexy de toi-même ?',
            'À quelle fréquence lavez-vous vos sous-vêtements ?',
            'Échangeriez-vous votre frère contre un million d’euros ?',
            'Échangeriez-vous votre chien contre un million d’euros ?',
            'Nommez dix parties du corps que votre partenaire aime embrasser.',
            'Dites une liste de 10 articles ou objets que vous avez achetés et que vous n’avez jamais utilisés ou regrettés d’avoir acheté.',
            'Si vous étiez le sexe opposé pendant une heure, que feriez-vous ?',
            'Décrivez le rêve le plus étrange que vous ayez fait dans votre vie.',
            'Avez-vous déjà été humilié ? Expliquez ce qui s’est passé et ce que vous avez ressenti.',
            'Quelle est la caractéristique physique pour laquelle on vous complimente le plus ?',
            'Quelle est cette chose que vous ne feriez jamais même si quelqu’un vous offrait tout l’argent du monde ?',
            'Quelle est la chose la plus folle qui vous soit arrivée dans un centre commercial ?',
            'Quelle est la chose la plus méchante que vous ayez faite dans votre vie ?',
            'Avez-vous déjà pensé à tromper votre petit ami ou votre petite amie ?',
            'Avez-vous déjà menti à votre partenaire à propos d’une situation sérieuse ?',
            'Quelle est la pire rumeur ou le pire ragot que vous ayez dit ou répété ?',
            'Quelle a été la blague la plus dégoûtante jamais faite avec quelqu’un ?',
            'Vous avez déjà uriné dans une piscine ?',
            'Quelle est la chose la plus stupide que vous ayez faite devant une foule ?',
            'Quelle est la chose la plus stupide que vous ayez dite à votre partenaire dans votre intimité ?',
            'Quelle est la chose la plus dingue que tu aies jamais faite au lit ?',
            'Qu’est-ce qui te fait craquer physiquement chez quelqu’un ?',
            'As-tu déjà eu un coup d’un soir ?',
            'As-tu déjà pensé à quelqu’un d’autre en embrassant ton partenaire ?',
            'Quelle est la chose la plus sexy que quelqu’un t’ait jamais dite ?',
            'As-tu déjà été surpris(e) en plein acte ?',
            'Raconte nous ton histoire de flirt la plus gênante.',
            'Quel est le texto le plus coquin que tu aies jamais envoyé ?',
            'As-tu déjà fait du nudisme ou couru nu en public ?',
            'Quel est ton type de lingerie préféré ?',
            'As-tu déjà essayé le jeu de rôle au lit ?',
            'Décris ce qui t’excite de manière bizarre.',
            'Raconte nous une phrase d’accroche gênante que tu as utilisée.',
            'Décris ton baiser le plus mémorable.',
            'Quel est ton site pour adultes préféré ?',
            'As-tu déjà fantasmé sur le partenaire d’un ami ?',
            'Raconte nous ton pire rendez-vous.',
            'Quelle est ta routine de plaisir en solo ?',
            'As-tu déjà surpris quelqu’un d’autre en plein acte ?',
            'Décris ton idéal d’une séance de préliminaires.',
            'Quel est le rêve le plus explicite que tu aies jamais eu ?',
            'Préfères-tu avoir trop chaud ou trop froid pendant l’amour ?',
            'Quelle est ta mésaventure sexuelle la plus gênante ?',
            'As-tu déjà craqué pour un parent d’un(e) pote ?',
            'Raconte une histoire drôle ou gênante liée à des bruits pendant l’amour.',
            'Quel est ton joujou pour adulte préféré ?',
            'As-tu déjà eu une aventure au boulot ?',
            'Décris ton kink ou ta pratique sexuelle préférée.',
            'As-tu déjà tenté un ménage à trois ?',
            'As-tu déjà eu un(e) sex friend ?',
            'Qu’est-ce que tu penses des relations libres ?',
            'As-tu déjà rêvé de ton/ta pote en mode érotique ?',
            'As-tu déjà été chopé(e) en train de mater du porno ?',
            'As-tu déjà utilisé des menottes ou des liens ?',
            'As-tu déjà eu un date avec un(e) inconnu(e) rencontré(e) sur le net ?',
            'Décris ta dernière aventure intime en trois mots.',
            'T’as déjà tenté le sexe par téléphone ou en vidéo ?',
            'Décris ton scénario de jeu de rôle préféré.',
            'T’as déjà été curieux à propos du BDSM ?',
            'Accepterais-tu des faveurs en échange d’argent ?',
            'As-tu déjà tourné une sextape ?',
            'Quel est l’endroit le plus risqué où tu as eu une aventure rapide ?',
            'Quelle est ta technique pour exciter ton partenaire ?',
            'As-tu déjà utilisé une application de rencontre pour des plans cul ?',
            'As-tu déjà pensé à essayer le changement de rôle au lit ?',
            'As-tu déjà eu des rapports sexuels avec une personne du même sexe que toi ?',
            'As-tu déjà fait du self bondage ?',
            'T\'es-tu déjà mis des choses dans les fesses, si oui lesquels ?',
            'As-tu testé des sexe-toys si oui lesquels ?',
            'As-tu déjà eu des envies d\'être fessée ?',
            'T\'es-tu déjà masturbé devant quelqu’un ?',
            'A quoi penses-tu quand tu fais l’amour ?',
            'A quoi penses-tu quand tu te masturbes ?',
            'Quel achat avez-vous réalisé qui a résulter en une simple perte d’argent ?',
            'Est-ce que tu as un meilleur ami ?',
            'Y-a-t’il quelque chose que tu as toujours prétendu aimer, mais que tu n’aimes finalement pas du tout ?',
            'Quelle est la pire chose que tu aies faite au travail ?',
            'C’est quoi ton plus gros Turn Off ?',
            'Qu’elle est le plus gros écart d’âge que tu aies eu avec un(e) partenaire sexuel ?',
            'Est-ce que la ‘taille’ compte ?',
            'Qu’elle est ton désir sexuel le plus déviant ?',
            'Qu’elle est la chose la plus embarrassante qui te soit arrivée pendant le sexe ?',
            'Qu’elle est ton plus gros Turn On ?',
            'Préfère-tu les gens bruyants ou silencieux au lit ?',
            'Qu’elle est ta chanson préférée à mettre dans la chambre au moment de l’acte ?',
            'Qu’elle est la chose la plus louche que quelqu’un trouverait en fouillant ton navigateur ?',
            'Qu’elle est la chose la plus folle que tu aies faite dans les transports en commun ?',
            'Si tu étais du sexe opposé pendant 1 jour... Que ferais-tu ?',
            'Qu’elle est la compétence inutile que tu aimerais apprendre tout de même ?',
            'Cite-nous la chose avec laquelle tu as du mal dans une relation amoureuse !',
            'Qu’elle est la meilleure chose que tu apporterais dans une relation amoureuse ?',
            'Qu’elle est la chose non sexuelle, qui pourtant te turn on ?',
            'Es-tu déjà sortie avec quelqu’un puis que tu as regretté par la suite ?',
            'Si vous êtes dans le BDSM, comment avez-vous découvert cela ?',
            'Ton avis à propos du sexe à la plage ?',
            'Quand es-tu le plus horny ?',
            'Combien de fois as-tu joui maximum, en une journée ?',
            'Combien de fois as-tu joui maximum, en une heure ?',
            'Qui serait dans ton orgie de rêve ?',
            'Qui inviterais-tu pour participer à une sex party ? Célébrités incluses.',
            'Si tu pouvais avoir du sexe avec une personne de ton passé, qui serait-ce ?',
            'Ton avis sur l’usage de sex-toys pendant l’acte ?',
            'Qu’elle est le lieu le plus étrange où tu te sois masturbé ?',
            'Qu’elle est ce truc sexuel que la plupart des gens aiment, mais que tu trouves surcoté ?',
            'Tu as un laissez-passer pour sortir avec une célébrité... Qui choisis-tu ?',
            'Si tu devais créer une position sexuelle encore inconnue, comment l’appellerais-tu ?',
            'Aimes-tu le Dirty Talk ?',
            'Qu’elle est la pensée la plus kinky que tu aies eue sur la personne qui a envoyé un message avant toi ?',
            'Aimerais-tu avoir un bandeau sur les yeux pendant l’acte ?',
            'T’es-tu déjà endormi pendant le sexe ?'
        ];

        // Vérifier que la liste des questions n'est pas vide
        if (questions.length === 0) {
            console.error('[Vérité] Erreur : Liste des questions vide');
            return interaction.reply({
                content: 'Erreur : Aucune question disponible. Contactez un administrateur.',
                ephemeral: true
            });
        }

        // Choisir une question aléatoire
        const randomQuestion = questions[Math.floor(Math.random() * questions.length)];

        // Répondre avec la question formatée
        try {
            await interaction.reply({
                content: `Répondez à cette question sincèrement : **${randomQuestion}**`,
                ephemeral: false
            });
        } catch (error) {
            console.error('[Vérité] Erreur lors de l’envoi de la réponse :', error.message);
            await interaction.reply({
                content: 'Erreur : Impossible d’afficher la question. Veuillez réessayer.',
                ephemeral: true
            });
        }
    },
};